### ISSUE TITLE
Not able to render content in Angular 13

### ISSUE THREAD

**Issue by TUSHARDM** [marcreichel/angular-carousel#6]
![image](https://user-images.githubusercontent.com/5736855/148631465-3e3c223a-0070-471c-8419-b1a76b947091.png)
I am not able to see my content rendered using the latest 13 version of angular. attached screenshot.
        "@angular/animations": "~13.0.0",
        "@angular/cdk": "^13.1.1",
        "@angular/common": "~13.0.0",
        "@angular/compiler": "~13.0.0",
        "@angular/core": "~13.0.0",
        "@angular/forms": "~13.0.0",
        "@angular/material": "~13.1.1",
        "@angular/material-moment-adapter": "~13.1.1",
        "@angular/platform-browser": "~13.0.0",
        "@angular/platform-browser-dynamic": "~13.0.0",

The HTML is as below
<angular-carousel>
    <ng-template *angularCarouselSlide>
        <ng-container>
            hello
        </ng-container>
    </ng-template>
    <ng-template *angularCarouselSlide>
        <ng-container>
            hello
        </ng-container>
    </ng-template>
    <ng-template *angularCarouselSlide>
        <ng-container>
            hello
        </ng-container>
    </ng-template>
</angular-carousel>

**Comment by TUSHARDM** [comment]
https://stackblitz.com/edit/angular-ivy-y5hlpq?file=package.json
https://angular-ivy-y5hlpq.stackblitz.io

**Comment by marcreichel** [comment]
Currently, this package is developed and tested with Angular 12. But I will look into this issue with Angular 13. Thanks for opening this issue!

**Comment by marcreichel** [comment]
@TUSHARDM It seems the behavior changed somehow. When using `ng-container` instead of `ng-template` it works as expected.

So:

```html
<angular-carousel>
    <ng-template *angularCarouselSlide>Content 1</ng-template>
    <ng-template *angularCarouselSlide>Content 2</ng-template>
    <ng-template *angularCarouselSlide>Content 3</ng-template>
</angular-carousel>
```

becomes:

```html
<angular-carousel>
    <ng-container *angularCarouselSlide>Content 1</ng-container>
    <ng-container *angularCarouselSlide>Content 2</ng-container>
    <ng-container *angularCarouselSlide>Content 3</ng-container>
</angular-carousel>
```

See: https://stackblitz.com/edit/angular-ivy-qvp5js?file=src/app/app.component.html
And: https://angular-ivy-qvp5js.stackblitz.io

I will update the documentation accordingly.

**Comment by marcreichel** [comment]
Apparently, using everything else than `ng-template` works 👍🏼 So you can use `ng-container` or just a `div` 👍🏼 I have updated the docs accordingly. Sorry for the inconvenience.

**Comment by TUSHARDM** [comment]
Thank You very much for such a spontaneous and quick reply. really appreciate your solution I used it in below way in my code and its working exactly as expected. Again Thank you for such a nice work. you saved my Day! :-)

<angular-carousel [bullets]="false" [infinite]="false" [auto]="true" [duration]="2500">
    <ng-container *ngFor="let item of navItems; let i = index;">
    <ng-container *angularCarouselSlide>
        <div class="slider-content">
              <p>My Content {{i+1}}</p>
        </div>
      </ng-container>
    </ng-container> 
</angular-carousel>
