### ISSUE TITLE
Update to Angular 16

### ISSUE THREAD

**Issue by Penlane** [marcreichel/angular-carousel#80]
Hi, I love using this component. It's simple, looks good and low-weight :)

Could you please update it so it's usable without npm-errors in more recent Angular versions?

Thank you!

**Comment by marcreichel** [comment]
@Penlane Thanks for those kind words! I really appreciate it!

I'm very happy to accept PRs to tackle this as I myself have not worked with Angular for over 1 1/2 years now to be honest.

**Comment by marcreichel** [comment]
@Penlane Tagged as version 3.0.0. Please let me know if everything is working as expected.

**Comment by marcreichel** [comment]
@Penlane The update is tagged as version 3.0.0. Please let me know if everything is working as expected. As mentioned above I've not worked with Angular for some time now, so I do not have a working Angular dev environment right now to test it myself.

**Comment by Penlane** [comment]
Thank you for tackling this so quickly!

I tried it out and it looks like the npm version 3.0.0 might not be up2date?

The npm tarball still has Angular 12 as a dependency: https://registry.npmjs.org/@marcreichel/angular-carousel/-/angular-carousel-3.0.0.tgz

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving:myProj@0.0.0
npm ERR! Found: @angular/common@16.1.7
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^16.1.7" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^12.0.0" from @marcreichel/angular-carousel@3.0.0
npm ERR! node_modules/@marcreichel/angular-carousel
npm ERR!   @marcreichel/angular-carousel@"3.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by marcreichel** [comment]
@Penlane My bad. I've fixed the missing dependencies and tagged it as version 3.0.1. Check with the updated version again please.
